title: Henry's Awesome Blog
author: Henry Thompson
email: your-19thompsonh@badinhs.org
description: > # this means to ignore newlines until "baseurl:"
  I created this blog on github for a school assignment in PAT 3 class.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
